### ISSUE TITLE
Does the ^% rewrite rule fire?

### ISSUE THREAD

**Issue by gilgamec** [Bodigrim/mod#14]
A simple example:

```haskell
{-# language ScopedTypeVariables #-}
{-# language RankNTypes #-}

import Data.Mod
import Data.Proxy
import GHC.Natural
import GHC.TypeNats hiding ( Mod(..) )

e,n,msg :: Natural
e = 35954996171344944356088924593542576361517455332243067
n = 53932494257017416534133387405057892857322884506118267
msg = 40511415361412953977729088020603939101623107

main = print $ rsa (e,n) msg

rsa :: (Natural, Natural) -> Natural -> Natural
rsa (e,n) m = case someNatVal n of
  SomeNat (_ :: Proxy p) -> unMod ((fromIntegral m ^ e) :: Mod p)
```

No matter what optimization flags I use, the exponentiation is always done by `GHC.Real.^` (as I can see by inspecting the STG).  I expect that the rewrite rules for (^%) should have fired, leading to the exponentiation being done by `powModNatural`. Are they firing?

**Comment by Bodigrim** [comment]
Thanks for catching this. It seems rules are not firing, and I don't know why. Maybe because of a funny type of `x`?..
https://github.com/Bodigrim/mod/blob/15dbe3e455df586aa0db20fe6a081cff79fce72e/Data/Mod.hs#L314
Unless there are other ideas, I'll probably just remove the rule and fix documentation.

**Comment by Bodigrim** [comment]
Filed as https://gitlab.haskell.org/ghc/ghc/-/issues/21093
