### ISSUE TITLE
Wrong results with GHC-9.4.4

### ISSUE THREAD

**Issue by larskuhtz** [Bodigrim/mod#25]
With GHC-9.4.4 and optimization enabled (`-O1` or `-O2`) I have been observing erroneous results for `newtype`s over `Mod q` for $q \geq 2^{64}$.

The behavior is somewhat non-deterministic and doesn't show up all the time. I have been able to reproduce it consistently (both on MacOS and Linux) with the following program:

```haskell
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE TypeApplications #-}
{-# OPTIONS_GHC -fno-warn-orphans #-}

module Main (main) where

import Data.Mod (Mod)
import GHC.TypeNats (KnownNat)
import Numeric.Natural (Natural)
import Test.QuickCheck (Arbitrary, arbitrary)
import Test.QuickCheck.Instances ()

newtype Fq = Fq (Mod 18446744073709551616 {- 2^64 -}) deriving (Num)

instance KnownNat n => Arbitrary (Mod n) where
    arbitrary = fromIntegral <$> arbitrary @Natural

instance Arbitrary Fq where
    arbitrary = Fq <$> arbitrary

main :: IO ()
main = let Fq x = -1 in print x
```

(cf. https://gist.github.com/larskuhtz/c216e2fd9e6aac580ea9640d554dddf8)

This program is expected to print `18446744073709551615`, but it prints `0` when compiled with optimizations enabled. I tested this with the latest version of the `mod` package.

The redundant `Arbitrary` instances are required in this example for the bug to manifest. However, I've also observed the issue in larger production code bases that didn't include `Arbitrary` instances for `Mod` and `Fq`.

**Comment by Bodigrim** [comment]
The test suite of `mod` specifically covers arithmetic on `Mod 2^64`:
https://github.com/Bodigrim/mod/blob/a1853c2692357642023d355092a8939345e23d55/test/Test.hs#L69-L71

The symptoms suggest that this is a bug in GHC 9.4 series, and indeed
```
$ cabal run -w ghc-9.2.6 Main.hs
18446744073709551615
$ cabal run -w ghc-9.4.4 Main.hs
0
$ cabal run -w ghc-9.6.0.20230210 --allow-newer Main.hs
18446744073709551615
```

@larskuhtz could you please raise an issue at https://gitlab.haskell.org/ghc/ghc/-/issues? It seems like the bug has been already fixed in GHC 9.6.0, but it would be nice to identify the fix and backport it to GHC 9.4 series.

@hsyl20 any ideas about this?

**Comment by larskuhtz** [comment]
@Bodigrim thanks for verifying. Here is the  GHC issue: https://gitlab.haskell.org/ghc/ghc/-/issues/22998

**Comment by Bodigrim** [comment]
Closing, this is an upstream issue.
